apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    app: jenkins
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  # Pin to the PVC created by the jenkins helm chart to prevent
  # other workloads from grabbing it.
  claimRef:
    name: jenkins
    namespace: jenkins
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/jenkins
    type: DirectoryOrCreate
